EM:
  ports:
  - 1070:1070/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  cpuset: 6,7
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/em-new:latest
  mem_limit: 8589934592
  environment:
    REDIS_HOST_IP: 10.6.51.144
    REDIS_PORT: 6379
    SENTINEL_IP: 10.6.51.144
    SENTINEL_PORT: 26379
    REDIS_MASTER: cm_mymaster01
  command:
  - /root/em_start.sh

A2:
  ports:
  - 1050:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  cpuset: 2,3
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/a2-new:latest
  mem_limit: 8589934592

C2:
  ports:
  - 1060:1060/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  cpuset: 8,9
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/c2-new:latest
  mem_limit: 8589934592
  environment:
    REDIS_HOST_IP: 10.6.51.144
    REDIS_PORT: 6379
    SENTINEL_PORT: 26379
    REDIS_MASTER: cm_mymaster01
  command:
  - /root/c2_start.sh

NM:
  ports:
  - 8081:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  cpuset: 14,15
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/nm-new:latest
  mem_limit: 8589934592
  environment:
    mts.baseurl: http://10.6.51.230:8082/mts-api/oem/v1
    mts.userdetails: /userDetails
    mts.host: 10.6.51.230
    mts.username: test
    mts.password: test
    mail.host: email-smtp.us-west-2.amazonaws.com
    mail.port: 25
    mail.username: AKIAJCTMSMITAE6GL6MQ
    mail.password: AsRbwvmHi9axd5TMWsl3OozFVGDxTaYdBPaIpeLw/NQ4
    mail.from: pankaj.bharambe@aeris.net
    mail.displayName: Aeris Communication

SML:
  ports:
  - 1090:1090/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  cpuset: 10,11
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/sml-new:latest
  mem_limit: 8589934592
  environment:
    REDIS_HOST_IP: 10.6.51.144
    REDIS_PORT: 6379
    SENTINEL_PORT: 26379
    REDIS_MASTER: cm_mymaster01
  command:
  - /root/sml_start.sh

SMH:
  ports:
  - 1010:1010/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  cpuset: 12,13
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/smh-new:latest
  mem_limit: 8589934592
  environment:
    REDIS_HOST_IP: 10.6.51.144
    REDIS_PORT: 6379
    SENTINEL_PORT: 26379
    REDIS_MASTER: cm_mymaster01
  command:
    - /root/smh_start.sh

API-GW:
  ports:
  - 1080:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  cpuset: 4,5
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/api-gw-new:latest
  mem_limit: 8589934592

MTS:
  ports:
  - 8082:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=non-core
  cpuset: 6,7,8
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/mts-new
  mem_limit: 8589934592

CAT:
  ports:
  - 8083:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=non-core
  cpuset: 3,4,5
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/cat-new
  mem_limit: 8589934592

MDB:
  ports:
  - 8084:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=non-core
  cpuset: 9,10,11
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/mdb
  mem_limit: 8589934592

NotesDB:
  ports:
  - 8050:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=non-core
  cpuset: 12,13,14
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/notesdb
  mem_limit: 8589934592

kafka:
  tty: true
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/kafka:0.10.0.0-2
  ports:
  - "9092:9092"
  volumes:
  - /opt/kafka/data:/opt/kafka/data
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=kafka_zookeeper
  environment:
    - ZK_SERVICE=zk
    - KAFKA_LOG_DIRS=/var/logs/kafkalogs
    - ADVERTISE_PUB_IP=10.6.51.40  
  links:
  - zk:zk

zk:
  tty: true
  image: rawmind/rancher-zk:3.4.6-1
  ports:
  - "2181:2181"
  volumes:
  - /opt/zk/data:/opt/zk/data
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=kafka_zookeeper
  
rabbit1:
  ports:
  - 15672:15672/tcp
  - 5672:5672/tcp
  labels:
    io.rancher.scheduler.affinity:host_label: services=rabbit
  hostname: rabbit1
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/rabbitmq
  
rabbit2:
  ports:
  - 5673:5672/tcp
  environment:
    CLUSTERED: 'true'
    CLUSTER_WITH: rabbit1
  labels:
    io.rancher.scheduler.affinity:host_label: services=rabbit
  hostname: rabbit2
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/rabbitmq
  links:
  - rabbit1:rabbit1

Redis:
  ports:
    - "6379:6379"
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/redis:3
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=redis
    
Sentinel:
  ports:
    - "26379:26379"
  links: 
  - redis:redis 
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/sentinel:3
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=redis

nginx-tcp1:
  ports:
  - 1012:1012/tcp
  - 1013:1013/tcp
  - 1014:1014/tcp
  - 1015:1015/tcp
  - 1883:1883/tcp
  - 80:80/tcp
  - 8083:8083/tcp
  - 8989:8989/tcp
  - 9443:9443/tcp
  labels:
    io.rancher.scheduler.affinity:host_label: services=nginx
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/nginx:qa-pge-1

    