em:
  ports:
  - 1070:1070/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/em-new:latest
  mem_limit: 8589934592
  environment:
    SENTINEL_PORT: 26379
    REDIS_MASTER: cm_mymaster01
    core-db:  
    core-db-port:
    core-db-name: 
  links:
  - smh:smh
  - ibus:ibus
  - mts:mts
  - ebus:ebus
  - cache-db:cache-db
  command:
  - /root/em_start.sh

a2:
  ports:
  - 1050:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/a2-new:latest
  mem_limit: 8589934592
  environment:
    REDIS_MASTER: cm_mymaster01
    a2-db: a2-db.aertass.com  
    a2-db-port: 1521
    a2-db-name: ORCL
    core-db: core-db.aertass.com  
    core-db-port: 1521
    core-db-name: ORCL
  links:
  - mdb:mdb
  - ibus:ibus
  - nm:nm
  - mts:mts
  - pa:pa
  - cache-db:cache-db
  - ebus:ebus

c2:
  ports:
  - 1060:1060/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/c2-new:latest
  mem_limit: 8589934592
  environment:
    REDIS_MASTER: cm_mymaster01
    core-db: core-db.aertass.com 
    core-db-port: 1521
    core-db-name: ORCL
  command:
  - /root/c2_start.sh
  links:
  - smh:smh
  - cache-db:cache-db
  - ibus:ibus
  - ebus:ebus

nm:
  ports:
  - 8081:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/nm-new:latest
  mem_limit: 8589934592
  environment:
    nm-db: nm-db.aertass.com 
    nm-db-port: 1521
    nm-db-name: ORCL
    nm_external_port: 8989
  links:
  - cat:cat
  - mdb-fe:mdb-fe
  - mts:mts
  - ibus:ibus
  - ebus:ebus

sml:
  ports:
  - 1090:1090/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/sml-new:latest
  mem_limit: 8589934592
  environment:
    REDIS_HOST_IP: 10.6.51.144
    REDIS_PORT: 6379
    SENTINEL_PORT: 26379
    REDIS_MASTER: cm_mymaster01
    core-db: core-db.aertass.com  
    core-db-port: 1521
    core-db-name: ORCL
  command:
  - /root/sml_start.sh
  links:
  - smh:smh
  - ibus:ibus
  - cache-db:cache-db
  - ebus:ebus

smh:
  ports:
  - 1010:1010/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/smh-new:latest
  mem_limit: 8589934592
  environment:
    REDIS_MASTER: cm_mymaster01
    core-db: core-db.aertass.com  
    core-db-port: 1521
    core-db-name: ORCL
  command:
    - /root/smh_start.sh
  links:
  - cache-db:cache-db
  - em:em
  - ibus:ibus
  - mdb:mdb
  - mts:mts
  - ebus:ebus

pa:
  ports:
  - 1080:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=core
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/api-gw-new:latest
  mem_limit: 8589934592
  environment:
    core-db: core-db.aertass.com  
    core-db-port: 1521
    core-db-name: ORCL
  links:
  - smh:smh
  - cat:cat
  - em:em
  - mdb:mdb
  - a2:a2
  - mts:mts
  - nm:nm
  - ibus:ibus
  - ebus:ebus

mts:
  ports:
  - 8082:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=non-core
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/mts-new
  mem_limit: 8589934592
  environment:
    mts-db: mts-db.aertass.com
    mts-db-port: 1521
    mts-db-name: ORCL
  links:
  - pa:pa
  - mdb:mdb
  - nm:nm
  - ebus:ebus

cat:
  ports:
  - 8083:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=non-core
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/cat-new
  mem_limit: 8589934592
  environment:
    cat-db: cat-db.aertass.com
    cat-db-port: 1521
    cat-db-name: ORCL
  links:
  - pa:pa
  - nm:nm
  - mts:mts
  - notesdb:notesdb
  - mdb-fe:mdb-fe
  - ebus:ebus

mdb:
  ports:
  - 8084:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=non-core
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/mdb
  mem_limit: 8589934592
  environment:
    mdb-db: mdb-db.aertass.com
    mdb-db-port: 1521
    mdb-db-name: ORCL
  links:
  - pa:pa
  - cat:cat
  - mts:mts
  - nm:nm
  - ebus:ebus
  - ibus:ibus

notesdb:
  ports:
  - 8050:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=non-core
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/notesdb
  mem_limit: 8589934592
  environment:
    notes-db: notes-db.aertass.com
    notes-db-port: 1521
    notes-db-name: ORCL
  links:
  - pa:pa
  - cat:cat
  - mts:mts
  - nm:nm
  - ibus:ibus
  - ebus:ebus 

ibus:
  tty: true
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/kafka:0.10.0.0-2
  ports:
  - "9092:9092"
  volumes:
  - /opt/kafka/data:/opt/kafka/data
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=kafka_zookeeper
  environment:
    - ZK_SERVICE=zk
    - KAFKA_LOG_DIRS=/var/logs/kafkalogs
    - ADVERTISE_PUB_IP=10.6.51.40  
  links:
  - zk:zk

zk:
  tty: true
  image: rawmind/rancher-zk:3.4.6-1
  ports:
  - "2181:2181"
  volumes:
  - /opt/zk/data:/opt/zk/data
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=kafka_zookeeper
  
ebus:
  ports:
  - 15672:15672/tcp
  - 5672:5672/tcp
  labels:
    io.rancher.scheduler.affinity:host_label: services=rabbit
  hostname: ebus
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/rabbitmq
  
ebus1:
  ports:
  - 5673:5672/tcp
  environment:
    CLUSTERED: 'true'
    CLUSTER_WITH: ebus
  labels:
    io.rancher.scheduler.affinity:host_label: services=rabbit
  hostname: ebus1
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/rabbitmq
  links:
  - ebus:ebus

redis:
  ports:
    - "6379:6379"
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/redis:3
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=redis
    
cache-db:
  ports:
    - "26379:26379"
  links: 
  - redis:redis 
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/sentinel:3
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: services=redis

nginx-tcp1:
  ports:
  - 1012:1012/tcp
  - 1013:1013/tcp
  - 1014:1014/tcp
  - 1015:1015/tcp
  - 1883:1883/tcp
  - 80:80/tcp
  - 8083:8083/tcp
  - 8989:8989/tcp
  - 9443:9443/tcp
  labels:
    io.rancher.scheduler.affinity:host_label: services=nginx
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/atsp/nginx:qa-pge-1
